config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "/:locale", locale: /en|id/, defaults: { locale: "en" } do
    resources :organizations, only: %i[ show edit update ] do
      resources :passwords, param: :token

      resource :session, except: %i[ destroy ]
    end

    resource :session, only: %i[ destroy ]

    resources :shift_attendances, except: %i[ edit destroy ], path: "shift-attendances"

    # Created via command line or recurring job
    resources :shift_occurences, only: %i[ index show destroy ], path: "shift-occurences"

    resources :shifts

    resources :team_shifts, path: "team-shifts"

    resources :teams

    resources :user_imports, except: %i[ edit update destroy ], path: "user-imports"

    resources :users, only: %i[ index ]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/user_import.rb
# frozen_string_literal: true

class UserImport < ApplicationRecord
  belongs_to :organization
  has_one_attached :file

  enum :status, %i[ waiting processing success failed ], validate: true

  validates :file,
    attached: true,
    limit: { min: 1, max: 1 },
    content_type: :csv,
    size: { less_than: 500.kilobytes }

  scope :where_status, ->(status) {
    if %w[ waiting processing success failed ].include?(status)
      where(status:)
    end
  }

  after_commit :process, on: :create

  def csv
    @csv ||= file.open { |f| CSV.parse(f.read, headers: true) }
  end

  private

  def process
    UserImportJob.perform_later(self)
  end
end

app/models/user_import/processing.rb
# frozen_string_literal: true

class UserImport::Processing
  def self.process(user_import)
    new(user_import).process
  end

  def initialize(user_import)
    @user_import = user_import
  end

  def process
    user_import.processing!

    ActiveRecord::Base.transaction do
      create_users
      user_import.update!(status: :success, imported_count: user_import.csv.size)
    end

  rescue StandardError => error
    user_import.update!(status: :failed, error: error.message)
  end

  private

  attr_reader :user_import

  def create_users
    user_import.csv.each do |row|
      organization = user_import.organization
      attributes = UserImport::Row.new(row).attributes

      user_values = attributes.except(:team).merge({ organization: })
      user = User.create!(user_values)

      team = Team.find_by!(organization:, name: attributes[:team])
      team.memberships.create!(user:, role: "member")
    end
  end
end

app/models/user_import/row.rb
# frozen_string_literal: true

class UserImport::Row
  def initialize(row)
    @row = row
  end

  def attributes
    {
      full_name: row["Full Name"],
      employee_number: row["Employee Number"],
      email_address: row["Email Address"],
      phone_number: row["Phone Number"],
      team: row["Team"],
      password: row["Phone Number"].gsub(/\D/, "")
    }
  end

  private

  attr_reader :row
end

app/controllers/user_imports_controller.rb
# frozen_string_literal: true

class UserImportsController < ApplicationController
  before_action :set_organization
  before_action :set_user_import, only: %i[ show ]

  def index
    authorize UserImport

    @user_imports = @organization
      .user_imports
      .includes(:file_attachment)
      .where_status(params[:status])
      .order(created_at: :desc)
  end

  def show
    authorize @user_import
  end

  def new
    authorize UserImport

    @user_import = @organization.user_imports.build
  end

  def create
    authorize UserImport

    @user_import = @organization
      .user_imports
      .build(user_import_params.merge({ status: "waiting" }))

    respond_to do |format|
      if @user_import.save
        format.html { redirect_to @user_import, notice: "User import was successfully created." }
        format.json { render :show, status: :created, location: @user_import }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_import.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_organization
    @organization = Organization.find(current_user.organization_id)
  end

  def set_user_import
    @user_import = @organization
      .user_imports
      .find(params.expect(:id))
  end

  def user_import_params
    params.expect(user_import: [ :file ])
  end
end

app/helpers/user_imports_helper.rb
# frozen_string_literal: true

module UserImportsHelper
end

app/views/user_imports/_form.html.erb
<%= form_with(model: user_import, class: "contents") do |form| %>
  <% if user_import.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(user_import.errors.count, "error") %> prohibited this user_import from being saved:</h2>

      <ul class="list-disc ml-6">
        <% user_import.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-6 text-sm">
    <%= form.label :file, "CSV File", class: "text-xs font-semibold uppercase tracking-wide text-neutral-500" %>
    <%= form.file_field :file, accept: "text/csv", class: ["block w-full sm:w-2/3 lg:w-1/2 min-h-9 mt-2 px-3 py-1.75 border shadow-xs", {"border-neutral-300 focus:outline-blue-600": user_import.errors[:file].none?, "border-red-400 focus:outline-red-600": user_import.errors[:file].any?}] %>
  </div>

  <div class="mt-8">
    <%= form.submit "Upload File", class: "w-full sm:w-auto min-h-9 px-4 py-2 bg-neutral-800 hover:bg-neutral-900 text-sm text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_imports/_user_import.html.erb
<div id="<%= dom_id user_import %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Status:</strong>
    <%= user_import.status %>
  </div>
  <div>
    <strong class="block font-medium mb-1">File:</strong>
    <%= link_to user_import.file.filename, user_import.file, class: "text-gray-700 underline hover:no-underline" if user_import.file.attached? %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= user_import.organization_id %>
  </div>
</div>

app/views/user_imports/index.html.erb
<% content_for :title, "User Imports" %>

<div class="w-full space-y-6">
  <%= render UserAndTeamManagements::HeaderComponent.new(active_tab: :user_imports) %>

  <%= turbo_frame_tag "user-imports-frame", class: "space-y-6", data: { turbo_action: "advance" } do %>
    <nav class="flex flex-col sm:flex-row justify-between items-center gap-2 sm:gap-4">
      <div class="w-full sm:w-32">
        <%= render PageReloadingSelectComponent.new(
          name: :status,
          url: user_imports_url,
          options: [
            ["All Statuses", "all"],
            ["Waiting", "waiting"],
            ["Processing", "processing"],
            ["Success", "success"],
            ["Failed", "failed"]
          ],
          selected: params[:status] || "all")
        %>
      </div>

      <div class="w-full sm:w-auto">
        <%= link_to(
          new_user_import_url,
          class: "flex justify-center items-center gap-2 px-4 py-2 bg-neutral-800
            hover:bg-neutral-900 transition-colors text-center text-sm text-white
            font-medium",
          data: {
            turbo_frame: "_top"
          }) do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus-icon lucide-plus size-4"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
          Import Users
        <% end %>
      </div>
    </nav>

    <section class="overflow-x-auto">
      <table class="table-fixed w-216 xl:w-full">
        <thead>
          <tr class="min-h-9 *:bg-neutral-100 border border-neutral-300">
            <th class="pl-4 py-2 text-left text-sm font-medium text-neutral-600">File Name</th>
            <th class="w-40 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Status</th>
            <th class="w-48 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Imported</th>
            <th class="w-56 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Uploaded</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-neutral-200 last:border-b last:border-neutral-200">
          <% if @user_imports.any? %>
            <% @user_imports.each do |import| %>
              <tr class="relative *:pl-4 *:py-4 *:text-sm">
                <td>
                  <%= link_to import, data: { turbo_frame: "_top" } do %>
                    <span class="absolute inset-0"></span>
                    <%= import.file.filename.to_s %>
                  <% end %>
                </td>
                <td><%= import.status %></td>
                <td><%= import.imported_count || 0 %></td>
                <td><%= l import.created_at.in_time_zone(@organization.time_zone) %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td
                colspan="4"
                class="py-4 text-center text-sm text-neutral-600 font-medium"
              >
                No data
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</div>

app/views/user_imports/new.html.erb
<% content_for :title, "New User Import" %>

<div class="w-full">
  <header class="w-full h-fit pb-4 border-b border-neutral-300 space-y-6">
    <nav class="flex items-center gap-2 text-sm font-medium text-neutral-500 [&>a]:hover:text-neutral-900 [&>a]:hover:underline">
      <%= link_to organization_url(@organization) do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house-icon lucide-house size-4"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>
      <% end %>
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right-icon lucide-chevron-right size-4"><path d="m9 18 6-6-6-6"/></svg>
      </div>
      <%= link_to "User Imports", user_imports_url %>
    </nav>

    <div class="space-y-2">
      <h1 class="font-semibold text-xl">Import Users</h1>
      <p class="text-sm text-neutral-500">
        Create multiple users at once by uploading a single CSV file
        (<%= link_to(
          "Download example",
          "#",
          class: "font-medium text-neutral-800 hover:text-neutral-900 underline")
        %>)
      </p>
    </div>
  </header>

  <%= render "form", user_import: @user_import %>
</div>

app/views/user_imports/show.html.erb
<% content_for :title, "Showing user import" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing user import</h1>

  <%= render @user_import %>

  <%= link_to "Back to user imports", user_imports_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>