config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "/:locale", locale: /en|id/, defaults: { locale: "en" } do
    resources :organizations, only: %i[ show edit update ] do
      resources :passwords, param: :token

      resource :session, except: %i[ destroy ]
    end

    resource :session, only: %i[ destroy ]

    resources :shift_attendances, except: %i[ edit destroy ], path: "shift-attendances"

    # Created via command line or recurring job
    resources :shift_occurences, only: %i[ index show destroy ], path: "shift-occurences"

    resources :shifts

    resources :team_shifts, path: "team-shifts"

    resources :teams

    resources :user_imports, except: %i[ edit update destroy ], path: "user-imports"

    resources :users, only: %i[ index ]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/team_shift.rb
# frozen_string_literal: true

class TeamShift < ApplicationRecord
  include Archivable

  belongs_to :team
  belongs_to :shift
end

app/controllers/team_shifts_controller.rb
# frozen_string_literal: true

class TeamShiftsController < ApplicationController
  before_action :set_organization
  before_action :set_team_shift, only: %i[ show edit update destroy ]

  def index
    authorize TeamShift

    @team_shifts = TeamShift
      .joins(team: :organization)
      .where(team: { organization: @organization })
  end

  def show
    authorize @team_shift
  end

  def new
    authorize TeamShift

    @team_shift = TeamShift.new
  end

  def edit
    authorize @team_shift
  end

  def create
    authorize TeamShift

    @team_shift = TeamShift.new(team_shift_params)

    respond_to do |format|
      if @team_shift.save
        format.html { redirect_to @team_shift, notice: "Team shift was successfully created." }
        format.json { render :show, status: :created, location: @team_shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @team_shift

    respond_to do |format|
      if @team_shift.update(team_shift_params)
        format.html { redirect_to @team_shift, notice: "Team shift was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @team_shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @team_shift

    @team_shift.archive

    respond_to do |format|
      format.html { redirect_to team_shifts_path, notice: "Team shift was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find(current_user.organization_id)
  end

  def set_team_shift
    @team_shift = TeamShift
      .joins(team: :organization)
      .where(team: { organization: @organization })
      .find(params.expect(:id))
  end

  def team_shift_params
    params.expect(team_shift: [ :team_id, :shift_id ])
  end
end

app/helpers/team_shifts_helper.rb
# frozen_string_literal: true

module TeamShiftsHelper
end

app/views/team_shifts/_form.html.erb
<%# locals: (team_shift:) %>

<%= form_with(model: team_shift, class: "contents") do |form| %>
  <% if team_shift.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(team_shift.errors.count, "error") %> prohibited this team_shift from being saved:</h2>

      <ul class="list-disc ml-6">
        <% team_shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": team_shift.errors[:team_id].none?, "border-red-400 focus:outline-red-600": team_shift.errors[:team_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :shift_id %>
    <%= form.text_field :shift_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": team_shift.errors[:shift_id].none?, "border-red-400 focus:outline-red-600": team_shift.errors[:shift_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/team_shifts/_team_shift.html.erb
<div id="<%= dom_id team_shift %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Team:</strong>
    <%= team_shift.team_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Shift:</strong>
    <%= team_shift.shift_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Archived at:</strong>
    <%= team_shift.archived_at %>
  </div>
</div>

app/views/team_shifts/edit.html.erb
<% content_for :title, "Editing team shift" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing team shift</h1>

  <%= render "form", team_shift: @team_shift %>

  <%= link_to "Show this team shift", @team_shift, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to team shifts", team_shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/team_shifts/index.html.erb
<% content_for :title, "Team shifts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Team shifts</h1>
    <%= link_to "New team shift", new_team_shift_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="team_shifts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @team_shifts.any? %>
      <% @team_shifts.each do |team_shift| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render team_shift %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", team_shift, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_team_shift_path(team_shift), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", team_shift, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No team shifts found.</p>
    <% end %>
  </div>
</div>

app/views/team_shifts/new.html.erb
<% content_for :title, "New team shift" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New team shift</h1>

  <%= render "form", team_shift: @team_shift %>

  <%= link_to "Back to team shifts", team_shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/team_shifts/show.html.erb
<% content_for :title, "Showing team shift" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing team shift</h1>

  <%= render @team_shift %>

  <%= link_to "Edit this team shift", edit_team_shift_path(@team_shift), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to team shifts", team_shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this team shift", @team_shift, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>