config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "/:locale", locale: /en|id/, defaults: { locale: "en" } do
    resources :organizations, only: %i[ show edit update ] do
      resources :passwords, param: :token

      resource :session, except: %i[ destroy ]
    end

    resource :session, only: %i[ destroy ]

    resources :shift_attendances, except: %i[ edit destroy ], path: "shift-attendances"

    # Created via command line or recurring job
    resources :shift_occurences, only: %i[ index show destroy ], path: "shift-occurences"

    resources :shifts

    resources :team_shifts, path: "team-shifts"

    resources :teams

    resources :user_imports, except: %i[ edit update destroy ], path: "user-imports"

    resources :users, only: %i[ index ]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/shift.rb
# frozen_string_literal: true

class Shift < ApplicationRecord
  include Archivable

  belongs_to :organization
  has_many :team_shifts, dependent: :destroy
  has_many :teams, through: :team_shifts
  has_many :occurences, class_name: "ShiftOccurence", dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :recurrence_rule, presence: true
  validates :effective_from, presence: true
  validates :effective_to, comparison: { greater_than: :effective_from }, allow_nil: true

  delegate :time_zone, to: :organization

  after_commit Shift::SavingCallback.new, on: %i[ create update ]

  def days
    @days ||= Shift::RecurrenceRuleParser.parse(recurrence_rule)
  end

  def duration
    if overnight?
      (end_time + 1.day) - start_time
    else
      end_time - start_time
    end
  end

  def overnight?
    start_time > end_time
  end

  def effective_from_in_time_zone
    effective_from.in_time_zone(time_zone)
  end
end

app/models/shift/future_occurences_generation.rb
# frozen_string_literal: true

class Shift::FutureOccurencesGeneration
  def self.generate_for(shift)
    tz = ActiveSupport::TimeZone[shift.time_zone]
    tomorrow = (tz.now + 1.day).beginning_of_day

    generate_for_after(shift, tomorrow)
  end

  def self.generate_for_after(shift, time)
    new(shift, time).generate_for_shift
  end

  def initialize(shift, time)
    @shift = shift
    @time = time
  end

  def generate_for_shift
    30.times.each do |i|
      start_at = positioned_time + i.days

      if create_for_starting_time?(start_at)
        create_with_starting_time(start_at)
      end
    end
  end

  private

  attr_reader :shift, :time

  def positioned_time
    hour = shift.start_time.hour
    minute = shift.start_time.min

    time.change(hour:, minute:).beginning_of_minute
  end

  def create_for_starting_time?(start_at)
    day = day_mapping[start_at.wday]

    start_at >= shift.effective_from_in_time_zone && shift.days.include?(day)
  end

  def create_with_starting_time(start_at)
    unless shift.occurences.exists?(start_at:)
      shift.occurences.create!(start_at:, end_at: start_at + shift.duration)
    end
  end

  def day_mapping
    %w[sunday monday tuesday wednesday thursday friday saturday]
  end
end

app/models/shift/future_occurences_removal.rb
# frozen_string_literal: true

class Shift::FutureOccurencesRemoval
  def self.remove_for(shift)
    tz = ActiveSupport::TimeZone[shift.time_zone]
    time = tz.now.end_of_day

    remove_for_after(shift, time)
  end

  def self.remove_for_after(shift, time)
    new(shift, time).remove_for_shift
  end

  def initialize(shift, time)
    @shift = shift
    @time = time
  end

  def remove_for_shift
    remove_future_occurences
  end

  private

  attr_reader :shift, :time

  def remove_future_occurences
    shift
      .occurences
      .where([ "start_at > :time", { time: } ])
      .delete_all
  end
end

app/models/shift/recurrence_rule_parser.rb
# frozen_string_literal: true

class Shift::RecurrenceRuleParser
  def self.parse(recurrence_rule)
    new(recurrence_rule).parse
  end

  def initialize(recurrence_rule)
    @recurrence_rule = recurrence_rule
  end

  def parse
    if recurrence_rule == "everyday"
      all_days
    elsif recurrence_rule == "weekdays"
      weekdays
    elsif recurrence_rule == "weekends"
      weekends
    else
      parse_comma_separated
    end
  end

  private

  attr_reader :recurrence_rule

  def all_days
    %w[ sunday monday tuesday wednesday thursday friday saturday ]
  end

  def weekdays
    %w[ monday tuesday wednesday thursday friday ]
  end

  def weekends
    %w[ saturday sunday ]
  end

  def parse_comma_separated
    days = []

    recurrence_rule.split(",").each do |day|
      case day
      when "sun"
        days << "sunday"
      when "mon"
        days << "monday"
      when "tue"
        days << "tuesday"
      when "wed"
        days << "wednesday"
      when "thu"
        days << "thursday"
      when "fri"
        days << "friday"
      when "sat"
        days << "saturday"
      else
        # no-op, skip invalid values
      end
    end

    days.uniq
  end
end

app/models/shift/saving_callback.rb
# frozen_string_literal: true

class Shift::SavingCallback
  def after_commit(shift)
    if affecting_future_occurences?(shift)
      ShiftFutureOccurencesGenerationJob.perform_later(shift)
    end
  end

  private

  def affecting_future_occurences?(shift)
    (shift.saved_changes.keys & triggering_keys).any?
  end

  def triggering_keys
    %w[ recurrence_rule effective_from effective_to start_time end_time ]
  end
end

app/controllers/shifts_controller.rb
# frozen_string_literal: true

class ShiftsController < ApplicationController
  before_action :set_organization
  before_action :set_shift, only: %i[ show edit update destroy ]

  def index
    authorize Shift

    @shifts = @organization.shifts.order(created_at: :desc)
  end

  def show
    authorize @shift
  end

  def new
    authorize Shift

    @shift = @organization.shifts.build
  end

  def edit
    authorize @shift
  end

  def create
    authorize Shift

    @shift = @organization.shifts.build(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @shift

    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: "Shift was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @shift

    @shift.archive

    respond_to do |format|
      format.html { redirect_to shifts_path, notice: "Shift was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find(current_user.organization_id)
  end

  def set_shift
    @shift = @organization.shifts.find(params.expect(:id))
  end

  def shift_params
    params.expect(shift: [ :name, :start_time, :end_time, :recurrence_rule, :effective_from, :effective_to ])
  end
end

app/helpers/shifts_helper.rb
# frozen_string_literal: true

module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%# locals: (shift:) %>

<%= form_with(model: shift, class: "contents") do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul class="list-disc ml-6">
        <% shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:name].none?, "border-red-400 focus:outline-red-600": shift.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_time %>
    <%= form.time_field :start_time, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:start_time].none?, "border-red-400 focus:outline-red-600": shift.errors[:start_time].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_time %>
    <%= form.time_field :end_time, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:end_time].none?, "border-red-400 focus:outline-red-600": shift.errors[:end_time].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :recurrence_rule %>
    <%= form.text_field :recurrence_rule, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:recurrence_rule].none?, "border-red-400 focus:outline-red-600": shift.errors[:recurrence_rule].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :effective_from %>
    <%= form.date_field :effective_from, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:effective_from].none?, "border-red-400 focus:outline-red-600": shift.errors[:effective_from].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :effective_to %>
    <%= form.date_field :effective_to, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift.errors[:effective_to].none?, "border-red-400 focus:outline-red-600": shift.errors[:effective_to].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<div id="<%= dom_id shift %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= shift.organization_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= shift.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Start time:</strong>
    <%= shift.start_time %>
  </div>
  <div>
    <strong class="block font-medium mb-1">End time:</strong>
    <%= shift.end_time %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Recurrence rule:</strong>
    <%= shift.recurrence_rule %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Effective from:</strong>
    <%= shift.effective_from %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Effective to:</strong>
    <%= shift.effective_to %>
  </div>
</div>

app/views/shifts/edit.html.erb
<% content_for :title, "Editing shift" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shift</h1>

  <%= render "form", shift: @shift %>

  <%= link_to "Show this shift", @shift, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shifts", shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shifts/index.html.erb
<% content_for :title, "Shifts" %>

<div class="w-full space-y-6">
  <header class="w-full h-fit pb-4 border-b border-neutral-300 space-y-6">
    <h1 class="font-semibold text-xl">Shift Schedules</h1>
  </header>

  <%= turbo_frame_tag "shifts-frame", class: "space-y-6", data: { turbo_action: "advance" } do %>
    <nav class="flex flex-col sm:flex-row justify-between items-center gap-2 sm:gap-4">
      <div class="w-full sm:w-72">
        <%= render PageReloadingSearchboxComponent.new(
          name: :q,
          text: "Search shift",
          url: shifts_url,
          value: params[:q])
        %>
      </div>

      <div class="w-full sm:w-auto">
        <%= link_to(
          new_shift_url,
          class: "flex justify-center items-center gap-2 px-4 py-2 bg-neutral-800
            hover:bg-neutral-900 transition-colors text-center text-sm text-white
            font-medium",
          data: {
            turbo_frame: "_top"
          }) do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus-icon lucide-plus size-4"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
          New Shift
        <% end %>
      </div>
    </nav>

    <section class="overflow-x-auto">
      <table class="table-fixed w-256 xl:w-full">
        <thead>
          <tr class="min-h-9 *:bg-neutral-100 border border-neutral-300">
            <th class="pl-4 py-2 text-left text-sm font-medium text-neutral-600">Name</th>
            <th class="w-56 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Days</th>
            <th class="w-32 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Start</th>
            <th class="w-32 pl-4 py-2 text-left text-sm font-medium text-neutral-600">End</th>
            <th class="w-32 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Effective From</th>
            <th class="w-32 pl-4 py-2 text-left text-sm font-medium text-neutral-600">Effective To</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-neutral-200 last:border-b last:border-neutral-200">
          <% if @shifts.any? %>
            <% @shifts.each do |shift| %>
              <tr class="relative *:pl-4 *:py-4 *:text-sm">
                <td>
                  <%= link_to shift, data: { turbo_frame: "_top" } do %>
                    <span class="absolute inset-0"></span>
                    <%= shift.name %>
                  <% end %>
                </td>
                <td class="space-y-5">
                  <%= shift.recurrence_rule %>
                </td>
                <td>
                  <%= l shift.start_time, format: :without_date %>
                </td>
                <td class="flex items-center gap-2">
                  <%= l shift.end_time, format: :without_date %>

                  <% if shift.overnight? %>
                    <span class="px-1 py-0.5 bg-amber-100 border border-amber-200 text-xs">
                      +1 day
                    </span>
                  <% end %>
                </td>
                <td>
                  <%= l shift.effective_from %>
                </td>
                <td>
                  <%= shift.effective_to.present? ? l(shift.effective_to) : "-" %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td
                colspan="6"
                class="py-4 text-center text-sm text-neutral-600 font-medium"
              >
                No data
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</div>

app/views/shifts/new.html.erb
<% content_for :title, "New shift" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shift</h1>

  <%= render "form", shift: @shift %>

  <%= link_to "Back to shifts", shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shifts/show.html.erb
<% content_for :title, "Showing shift" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing shift</h1>

  <%= render @shift %>

  <%= link_to "Edit this shift", edit_shift_path(@shift), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shifts", shifts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this shift", @shift, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>