config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "/:locale", locale: /en|id/, defaults: { locale: "en" } do
    resources :organizations, only: %i[ show edit update ] do
      resources :passwords, param: :token

      resource :session, except: %i[ destroy ]
    end

    resource :session, only: %i[ destroy ]

    resources :shift_attendances, except: %i[ edit destroy ], path: "shift-attendances"

    # Created via command line or recurring job
    resources :shift_occurences, only: %i[ index show destroy ], path: "shift-occurences"

    resources :shifts

    resources :team_shifts, path: "team-shifts"

    resources :teams

    resources :user_imports, except: %i[ edit update destroy ], path: "user-imports"

    resources :users, only: %i[ index ]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/shift_attendance.rb
# frozen_string_literal: true

class ShiftAttendance < ApplicationRecord
  belongs_to :organization
  belongs_to :user
  belongs_to :shift_occurence

  validates :clock_in_at, presence: true
  validates :location, presence: true
  validate :clock_out_at_cannot_be_changed_after_set, on: :update

  private

  def clock_out_at_cannot_be_changed_after_set
    if persisted? && clock_out_at_changed? && clock_out_at_was.present?
      errors.add(:clock_out_at, "cannot be changed after the value was set")
    end
  end
end

app/controllers/shift_attendances_controller.rb
# frozen_string_literal: true

class ShiftAttendancesController < ApplicationController
  before_action :set_organization
  before_action :set_shift_attendance, only: %i[ show update ]

  def index
    @shift_attendances = @organization.shift_attendances.all
  end

  def show
  end

  def new
    @shift_attendance = @organization.shift_attendances.build(user: current_user)
  end

  def create
    @shift_attendance = @organization.shift_attendances.build(shift_attendance_creation_params.merge(user: current_user, clock_in_at: Time.now))

    respond_to do |format|
      if @shift_attendance.save
        format.html { redirect_to @shift_attendance, notice: "Shift attendance was successfully created." }
        format.json { render :show, status: :created, location: @shift_attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    clock_out = shift_attendance_clock_out_params[:clock_out]

    respond_to do |format|
      if clock_out && @shift_attendance.update(clock_out_at: Time.now)
        format.html { redirect_to @shift_attendance, notice: "Shift attendance was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @shift_attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_organization
    @organization = Organization.find(current_user.organization_id)
  end

  def set_shift_attendance
    @shift_attendance = @organization.shift_attendances.find(params.expect(:id))
  end

  def shift_attendance_creation_params
    params.expect(shift_attendance: [ :shift_occurence_id, :location ])
  end

  def shift_attendance_clock_out_params
    params.expect(shift_attendance: [ :clock_out ])
  end
end

app/helpers/shift_attendances_helper.rb
# frozen_string_literal: true

module ShiftAttendancesHelper
end

app/views/shift_attendances/_form.html.erb
<%# locals: (shift_attendance:) %>

<%= form_with(model: shift_attendance, class: "contents") do |form| %>
  <% if shift_attendance.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(shift_attendance.errors.count, "error") %> prohibited this shift_attendance from being saved:</h2>

      <ul class="list-disc ml-6">
        <% shift_attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:organization_id].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:organization_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:user_id].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :shift_occurence_id %>
    <%= form.text_field :shift_occurence_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:shift_occurence_id].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:shift_occurence_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :clock_in_at %>
    <%= form.datetime_field :clock_in_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:clock_in_at].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:clock_in_at].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :clock_out_at %>
    <%= form.datetime_field :clock_out_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:clock_out_at].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:clock_out_at].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shift_attendance.errors[:location].none?, "border-red-400 focus:outline-red-600": shift_attendance.errors[:location].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/shift_attendances/_shift_attendance.html.erb
<div id="<%= dom_id shift_attendance %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= shift_attendance.organization_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= shift_attendance.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Shift occurence:</strong>
    <%= shift_attendance.shift_occurence_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Clock in at:</strong>
    <%= shift_attendance.clock_in_at %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Clock out at:</strong>
    <%= shift_attendance.clock_out_at %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Location:</strong>
    <%= shift_attendance.location %>
  </div>
</div>

app/views/shift_attendances/edit.html.erb
<% content_for :title, "Editing shift attendance" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shift attendance</h1>

  <%= render "form", shift_attendance: @shift_attendance %>

  <%= link_to "Show this shift attendance", @shift_attendance, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shift attendances", shift_attendances_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shift_attendances/index.html.erb
<% content_for :title, "Shift attendances" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Shift attendances</h1>
  </div>

  <div id="shift_attendances" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @shift_attendances.any? %>
      <% @shift_attendances.each do |shift_attendance| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render shift_attendance %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", shift_attendance, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No shift attendances found.</p>
    <% end %>
  </div>
</div>

app/views/shift_attendances/new.html.erb
<% content_for :title, "New shift attendance" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shift attendance</h1>

  <%= render "form", shift_attendance: @shift_attendance %>

  <%= link_to "Back to shift attendances", shift_attendances_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shift_attendances/show.html.erb
<% content_for :title, "Showing shift attendance" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing shift attendance</h1>

  <%= render @shift_attendance %>

  <%= link_to "Back to shift attendances", shift_attendances_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>